In [2]:
import numpy as np
"""1. Scalar Operations
Create a scalar s with value 7.

Create a 1D array arr with values [2, 4, 6, 8].

Add s to each element of arr and print the result.

Multiply each element of arr by s and print the result.

"""
s=7
x=np.array([2,4,6,8])
print(x+s)
print(x*s)
#scalar operations impact each element of a matrix

[ 9 11 13 15]
[14 28 42 56]


In [6]:
"""
Create a 2D array matrix representing:

3  4
5  6

Print the array and its shape using matrix.shape.

"""
y=np.array(([3,4],[5,6]))
print(y,y.shape)
#.sape gives dimensionality, roes,cols

[[3 4]
 [5 6]] (2, 2)


In [9]:
"""
Create two 1D arrays: a = np.array([2, 3, 4]) and b = np.array([5, 6, 7]).

Compute and print their element-wise sum and product.

Create a 2D array c = np.array([[2, 3], [4, 5]]) and subtract 1 from each element.

"""
a=np.array([2,3,4])
b=np.array([5,6,7])
print(a+b,a*b)
c=np.array(([2,3],[4,5]))
print(c-1)
#scalar operations can impact all shapes of matrices

[ 7  9 11] [10 18 28]
[[1 2]
 [3 4]]


In [10]:
"""
Use np.random.randint(1, 20, size=4) to create a 1D array of 4 random integers between 1 and 19.

Multiply each element by 5 and print the result.

"""
z=np.random.randint(1,20,size=4)
print(z*5)
#useage of np.random.randint, with matrix of size 4

[70 65 85 85]


In [11]:
print(z)

[14 13 17 17]


In [20]:
"""
Create a 1D array d = np.array([1, 2, 3]) and a 2D array e = np.array([[4, 5], [6, 7], [8, 9]]).

Try adding d and e together using d + e. What happens? Why? (Hint: NumPy’s broadcasting adjusts shapes if possible—check the result!)

"""
d=np.array([1,2,3])
f=np.array([1,2])
g=np.array(([1],[2]))
e=np.array(([4,5],[6,7],[8,9]))


In [17]:
print(d+e)

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [18]:
print(f+e)


[[ 5  7]
 [ 7  9]
 [ 9 11]]


In [19]:
print(g+e)

ValueError: operands could not be broadcast together with shapes (2,1) (3,2) 

In [21]:
"""
Create vectors u = [2, -1, 4] and v = [0, 3, -2].

Compute their sum and difference.

Multiply u by 2 and v by -1.

"""
u=np.array([2,-1,4])
v=np.array([0,3,-2])
print(v+u)
print(v-u)
print(u*2)
print(v*-1)

[2 2 2]
[-2  4 -6]
[ 4 -2  8]
[ 0 -3  2]


In [24]:
"""
Using u and v from above:
Find their dot product.

Calculate their magnitudes.

Compute the angle between them (hint: use cosθ = (u • v) / (||u|| * ||v||) and np.arccos()).

"""
print(np.dot(u,v))#tells how aligned both the vectors are
print(np.linalg.norm(u))
print(np.linalg.norm(v))
#norm is magnitude(found using pytha theorem)
x=np.dot(u,v)/(np.linalg.norm(u)*np.linalg.norm(v))
print(np.arccos(x))

-11
4.58257569495584
3.605551275463989
2.2992952041945536


In [25]:
"""
Create w = [1, 2, 3].

Normalize it (divide by its norm) so its magnitude becomes 1.

Check that the new norm is 1.

Create two 2D vectors that are perpendicular (e.g., [1, 0] and [0, 1]).

Verify their dot product is zero.

"""

w=np.array([1,2,3])
l=w/(np.linalg.norm(w))
print(l)
print(np.linalg.norm(l))
m=np.array([1,0])
n=np.array([0,2])
print(np.dot(m,n))


[0.26726124 0.53452248 0.80178373]
1.0
0


In [26]:
"""
Create two 4D vectors (e.g., [1, 2, 3, 4] and [0, -1, 2, -3]).

Compute their sum, dot product, and angle.

"""
a=np.array([1,2,3,4])
b=np.array([0,-1,2,-3])
print(a+b)
dotp=np.dot(a,b)
a_norm=np.linalg.norm(a)
b_norm=np.linalg.norm(b)
print(np.arccos(dotp/(a_norm*b_norm)))

[1 1 5 1]
1.971818941644976
