In [2]:
import numpy as np

"""
Create matrices C = [[2, -1], [0, 3]] and D = [[4, 1], [2, 5]].

Compute C + D and C - D.

Compute 3 * C and -2 * D.

Using A and B from the example:
Compute A @ B and B @ A. Are they equal?

Define E = [[1, 2, 3], [4, 5, 6]] (2x3) and F = [[7, 8], [9, 10], [11, 12]] (3x2). Compute E @ F.

"""


'\nCreate matrices C = [[2, -1], [0, 3]] and D = [[4, 1], [2, 5]].\n\nCompute C + D and C - D.\n\nCompute 3 * C and -2 * D.\n\nUsing A and B from the example:\nCompute A @ B and B @ A. Are they equal?\n\nDefine E = [[1, 2, 3], [4, 5, 6]] (2x3) and F = [[7, 8], [9, 10], [11, 12]] (3x2). Compute E @ F.\n\n'

In [3]:
c=np.array(([2,-1],[0,3]))
d=np.array(([4,1],[2,5]))
print(c+d)

[[6 0]
 [2 8]]


In [4]:
print(c-d)

[[-2 -2]
 [-2 -2]]


In [5]:
print(3*c)

[[ 6 -3]
 [ 0  9]]


In [6]:
print(-2*d)

[[ -8  -2]
 [ -4 -10]]


In [7]:
print(c @ d)
print(d @ c)
#applying a linear transformation upon another might not lead to the same result

[[ 6 -3]
 [ 6 15]]
[[ 8 -1]
 [ 4 13]]


In [8]:
e=np.array(([1, 2, 3], [4, 5, 6]))
f=np.array(([7, 8], [9, 10], [11, 12]))
print(e @ f)
#becoz num of cols in first array is same as rows in second

[[ 58  64]
 [139 154]]


In [9]:
print(f @ e)

[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


In [10]:
"""
Create G = [[1, 2], [3, 4], [5, 6]] (3x2).

Compute G.T.

Verify that (G.T).T equals G.

Use np.eye(3) to create a 3x3 identity matrix.

Multiply it by a 3x3 matrix of your choice. What do you notice?

Define H = [[1, 2], [3, 4]] and vector v = [5, 6].

Compute H @ v.

"""

g=np.array(([1, 2], [3, 4], [5, 6]))
f=g.T
print(g)
print(f)


[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [11]:
print(np.eye(3))
print(np.array(([1,2,3],[4,5,6],[7,8,9]))*np.eye(3))
#only the diagonal stays the same

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


In [12]:
h=np.array(([1,2],[3,4]))
v=np.array([5,6])
print(h @ v)

[17 39]


In [16]:
"""

3x + 2y = 5 \\
x - y = 1


x+2y+3z=6
x−y+z=1
x+y−2z=2

x+y=3
2x+2y=6
x+y=4



"""

const=np.array(([3,2],[1,-1]))
equated=np.array(([5,1]))
x,y=np.linalg.solve(const,equated)
z=np.array([x,y])
print(z)
print(const @ z)#checking the answer

1.4000000000000001 0.39999999999999997
[5. 1.]


In [21]:
const=np.array(([1,2,3],[1,-1,1],[1,1,-2]))
equated=np.array([6,1,2])
x,y,z=np.linalg.solve(const,equated)
z=np.array([x,y,z])
print(z)
print(const @ z)

[1.76923077 1.30769231 0.53846154]
[6. 1. 2.]


In [23]:
const=np.array(([1,1],[2,2],[1,1]))
equated=np.array([3,6,4])
print(np.linalg.solve(const,equated))#no possible intersections therefore no ans, error raised is last 2 dimensions of the array must be square

LinAlgError: Last 2 dimensions of the array must be square

In [25]:
"""
x+y=3
2x+2y=6

x+y+z=6
2x−y+3z=9


"""
const=np.array(([1,1],[2,2]))
equated=np.array([3,6])
print(np.linalg.solve(const,equated))#infinitely many solutions, error raised is singular matrix

LinAlgError: Singular matrix

In [26]:
const=np.array(([1,1,1],[2,-1,3]))
equated=np.array([6,9])
print(np.linalg.solve(const,equated))#x,y,z equated to only 2 numbers

LinAlgError: Last 2 dimensions of the array must be square

In [27]:
const=np.array(([1,1],[2,-1]))
equated=np.array([6,9])
print(np.linalg.solve(const,equated))#


[5. 1.]
