In [2]:
"""
Define B=[4123]B = \begin{bmatrix} 4 & 1 \\ 2 & 3 \end{bmatrix}B = \begin{bmatrix} 4 & 1 \\ 2 & 3 \end{bmatrix}
.

Calculate its determinant.

Find its inverse and verify B@B−1=IB @ B^{-1} = IB @ B^{-1} = I
.

Define C=[1200312−14]C = \begin{bmatrix} 1 & 2 & 0 \\ 0 & 3 & 1 \\ 2 & -1 & 4 \end{bmatrix}C = \begin{bmatrix} 1 & 2 & 0 \\ 0 & 3 & 1 \\ 2 & -1 & 4 \end{bmatrix}
.

Compute det(C)\text{det}(C)\text{det}(C)
.

Find C−1C^{-1}C^{-1}
 and check the result.
"""


'\nDefine B=[4123]B = \x08egin{bmatrix} 4 & 1 \\ 2 & 3 \\end{bmatrix}B = \x08egin{bmatrix} 4 & 1 \\ 2 & 3 \\end{bmatrix}\n.\n\nCalculate its determinant.\n\nFind its inverse and verify B@B−1=IB @ B^{-1} = IB @ B^{-1} = I\n.\n\nDefine C=[1200312−14]C = \x08egin{bmatrix} 1 & 2 & 0 \\ 0 & 3 & 1 \\ 2 & -1 & 4 \\end{bmatrix}C = \x08egin{bmatrix} 1 & 2 & 0 \\ 0 & 3 & 1 \\ 2 & -1 & 4 \\end{bmatrix}\n.\n\nCompute det(C)\text{det}(C)\text{det}(C)\n.\n\nFind C−1C^{-1}C^{-1}\n and check the result.\n'

In [4]:
import numpy as np
b=np.array(([4,1],[2,3]))
x=np.linalg.det(b)
print(x)
if x!=0:
  inv=np.linalg.inv(b)
  print(inv)
  print(b @ inv)


10.000000000000002
[[ 0.3 -0.1]
 [-0.2  0.4]]
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


In [6]:
c=np.array(([1,2,0],[0,3,1],[2,-1,4]))
x=np.linalg.det(c)
print(x)
print(np.linalg.inv(c))
print(c @ np.linalg.inv(c) )

17.0
[[ 0.76470588 -0.47058824  0.11764706]
 [ 0.11764706  0.23529412 -0.05882353]
 [-0.35294118  0.29411765  0.17647059]]
[[ 1.00000000e+00 -1.11022302e-16 -2.77555756e-17]
 [-5.55111512e-17  1.00000000e+00  2.77555756e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [8]:
d=np.array(([1,2],[2,4]))
x=np.linalg.det(d)
print(x)
y=np.linalg.inv(d)
print(y)
print(d @ y)#det is 0 ie squished into a smaller dimension because of linear dependency, therefore infinitely many sols therefore singular matrix

0.0


LinAlgError: Singular matrix

In [11]:
"""
For the system:
{
x + 2y = 5 \\
3x + 4y = 11
\end{cases}\begin{cases}
x + 2y = 5 \\
3x + 4y = 11
\end{cases}

Represent it as Ax=bA \mathbf{x} = \mathbf{b}A \mathbf{x} = \mathbf{b}
.

Solve using x=A−1@b\mathbf{x} = A^{-1} @ \mathbf{b}\mathbf{x} = A^{-1} @ \mathbf{b}
 instead of np.linalg.solve().


Take E=[2003]E = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}E = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}
.

Compute its determinant and inverse.

Multiply ( E ) by a scalar (e.g., 2) and recompute. How do the determinant and inverse change?

"""

const=np.array(([1,2],[3,4]))
equated=np.array([5,11])
x,y=np.linalg.solve(const,equated)
print(x,y)
print(const @ np.array([x,y]))

1.0 2.0
[ 5. 11.]


In [14]:
const_inv=np.linalg.inv(const)
print(const_inv)
print(const_inv @ equated)#using the inverse also gives you the values of x and y

[[-2.   1. ]
 [ 1.5 -0.5]]
[1. 2.]


In [33]:
e=np.array(([2,0],[0,3]))
e_det=np.linalg.det(e)
e_inv=np.linalg.inv(e)
print(e_det,"\n",e_inv)
print(e @ e_inv)



6.0 
 [[0.5        0.        ]
 [0.         0.33333333]]
[[1. 0.]
 [0. 1.]]


In [27]:
e=e * 2
e_det=np.linalg.det(e)#12*2 or 6*2*2
e_inv=np.linalg.inv(e)
print(e_det,"\n",e_inv)
print(e @ e_inv)

23.999999999999993 
 [[0.25       0.        ]
 [0.         0.16666667]]
[[1. 0.]
 [0. 1.]]


In [29]:
e=e * 3
e_det=np.linalg.det(e)#18*3 or 6*3*3
e_inv=np.linalg.inv(e)
print(e_det,"\n",e_inv)
print(e @ e_inv)

54.00000000000001 
 [[0.16666667 0.        ]
 [0.         0.11111111]]
[[1. 0.]
 [0. 1.]]


In [32]:
e=e * 4
e_det=np.linalg.det(e)#24*4 or 6*4*4
e_inv=np.linalg.inv(e)
print(e_det,"\n",e_inv)
print(e @ e_inv)

1536.0000000000002 
 [[0.03125    0.        ]
 [0.         0.02083333]]
[[1. 0.]
 [0. 1.]]


In [34]:
e=e * -2
e_det=np.linalg.det(e)#6 * -2^2 #because it is 2 dimensional, if it was 3d it would mean cubed as area inc here and vol there
e_inv=np.linalg.inv(e)#Inverse of this is the original inverse divided by scalar again and again from t
print(e_det,"\n",e_inv)
print(e @ e_inv)

23.999999999999993 
 [[-0.25       -0.        ]
 [-0.         -0.16666667]]
[[1. 0.]
 [0. 1.]]


In [ ]:
"""
Define B=[4123]B = \begin{bmatrix} 4 & 1 \\ 2 & 3 \end{bmatrix}B = \begin{bmatrix} 4 & 1 \\ 2 & 3 \end{bmatrix}
.

Find its eigenvalues and eigenvectors.

Verify Av=λvA \mathbf{v} = \lambda \mathbf{v}A \mathbf{v} = \lambda \mathbf{v}
 for one pair.

2. 3x3 Matrix
Define C=[102020201]C = \begin{bmatrix} 1 & 0 & 2 \\ 0 & 2 & 0 \\ 2 & 0 & 1 \end{bmatrix}C = \begin{bmatrix} 1 & 0 & 2 \\ 0 & 2 & 0 \\ 2 & 0 & 1 \end{bmatrix}
.

Compute its eigenvalues and eigenvectors.

Check one pair.

3. Diagonal Matrix
Create D=[5000−20003]D = \begin{bmatrix} 5 & 0 & 0 \\ 0 & -2 & 0 \\ 0 & 0 & 3 \end{bmatrix}D = \begin{bmatrix} 5 & 0 & 0 \\ 0 & -2 & 0 \\ 0 & 0 & 3 \end{bmatrix}
.

Find its eigenvalues and eigenvectors. What do you notice about the eigenvalues?

4. Symmetric Matrix Property
Use A=[2112]A = \begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix}A = \begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix}
 from the example.

Confirm it’s symmetric (A=ATA = A^TA = A^T
).

Are the eigenvalues real? Are the eigenvectors orthogonal (dot product = 0)?

5. Scaling Effect
Take E=[1221]E = \begin{bmatrix} 1 & 2 \\ 2 & 1 \end{bmatrix}E = \begin{bmatrix} 1 & 2 \\ 2 & 1 \end{bmatrix}
.

Compute its eigenvalues and eigenvectors.

Multiply ( E ) by 2 and recompute. How do the eigenvalues change?

"""

In [39]:
b=np.array(([4,1],[2,3]))
eigenval,eigenvect=np.linalg.eig(b)
print(eigenval)
print(eigenvect)
v1=eigenvect[:,0]
v2=eigenvect[1]

[5. 2.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [42]:
print(b @ v1)
print(eigenval[0] * v1)

[3.53553391 3.53553391]
[3.53553391 3.53553391]


In [44]:
c=np.array(([1,0,2],[0,2,0],[2,0,1]))
eigenval,eigenvect=np.linalg.eig(c)
print(eigenval)
print(eigenvect)
v1=eigenvect[:,0]
print(c @ v1)
print(eigenval[0] * v1 )


[ 3. -1.  2.]
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.          0.          1.        ]
 [ 0.70710678  0.70710678  0.        ]]
[2.12132034 0.         2.12132034]
[2.12132034 0.         2.12132034]


In [47]:
d=np.array(([5,0,0],[0,-2,0],[0,0,3]))
eigenval,eigenvect=np.linalg.eig(d)
print(eigenval)
print(eigenvect)#for a diagonal matrix, the identity matrix is the eigenvector
v1=eigenvect[:,0]
print(d @ v1)
print(eigenval[0] * v1)

[ 5. -2.  3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[5. 0. 0.]
[5. 0. 0.]


In [49]:
e=np.array(([1,2],[2,1]))
eigenval,eigenvect=np.linalg.eig(e)
print(eigenval)
print(eigenvect)#for a diagonal matrix, the identity matrix is the eigenvector
v1=eigenvect[:,0]
print(e @ v1)
print(eigenval[0] * v1)

[ 3. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[2.12132034 2.12132034]
[2.12132034 2.12132034]


In [55]:
print(e,"\n",e.T)

[[1 2]
 [2 1]] 
 [[1 2]
 [2 1]]


In [61]:
print(np.dot([ 0.70710678, -0.70710678],[ 0.70710678 , 0.70710678]))#the eigen vectors of a symmetric matrix are orthoganal

0.0


In [62]:
e=e*2
eigenval,eigenvect=np.linalg.eig(e)
print(eigenval)
print(eigenvect)
v1=eigenvect[:,0]
print(e @ v1)
print(eigenval[0] * v1)#after scalar multiplication the eigen vectors did not change, however the eigen values doubled as well as the matrix vector product doubled

[ 6. -2.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[4.24264069 4.24264069]
[4.24264069 4.24264069]
